In [1]:
import numpy as np
import pandas as pd

In [3]:
train = pd.read_csv('https://raw.githubusercontent.com/kislay960/Data-Science-Practice/master/Train.csv')
test = pd.read_csv('https://raw.githubusercontent.com/kislay960/Data-Science-Practice/master/Test.csv')

In [4]:
train.head()

feature_1  feature_2  feature_3  feature_4  feature_5     target
0   0.293416  -0.945599  -0.421105   0.406816   0.525662 -82.154667
1  -0.836084  -0.189228  -0.776403  -1.053831   0.597997 -48.897960
2   0.236425   0.132836  -0.147723   0.699854  -0.187364  77.270371
3   0.175312   0.143194  -0.581111  -0.122107  -1.292168  -2.988581
4  -1.693011   0.542712  -2.798729  -0.686723   1.244077 -37.596722

In [9]:
train = train.values

In [10]:
xtrain = train[:,:-1]

In [11]:
xtrain

array([[ 0.29341624, -0.94559871, -0.42110515,  0.40681602,  0.52566183],
       [-0.83608408, -0.18922804, -0.77640262, -1.05383124,  0.59799685],
       [ 0.23642511,  0.13283602, -0.14772298,  0.69985396, -0.18736416],
       ...,
       [ 1.04417694, -0.89920649,  1.73039905, -1.87105676,  0.44251965],
       [-1.2691729 , -0.00505216,  1.85766873, -1.08036482,  0.73633394],
       [-1.88400025, -0.84942743, -1.45227035,  0.48861308,  1.4595758 ]])

In [12]:
ones = np.ones((xtrain.shape[0],1))

In [13]:
xtrain = np.hstack((ones,xtrain))
xtrain

array([[ 1.        ,  0.29341624, -0.94559871, -0.42110515,  0.40681602,
         0.52566183],
       [ 1.        , -0.83608408, -0.18922804, -0.77640262, -1.05383124,
         0.59799685],
       [ 1.        ,  0.23642511,  0.13283602, -0.14772298,  0.69985396,
        -0.18736416],
       ...,
       [ 1.        ,  1.04417694, -0.89920649,  1.73039905, -1.87105676,
         0.44251965],
       [ 1.        , -1.2691729 , -0.00505216,  1.85766873, -1.08036482,
         0.73633394],
       [ 1.        , -1.88400025, -0.84942743, -1.45227035,  0.48861308,
         1.4595758 ]])

In [15]:
ytrain = train[:,-1]

In [23]:
def hypothesis(x,theta):
  return np.dot(x,theta)

def error(x,y,theta):
  error = 0.0
  n = x.shape[0]
  y_ = hypothesis(x,theta)
  error = np.sum((y-y_)**2)
  return error/n

def gradient(x,y,theta):
  y_ = hypothesis(x,theta)
  grad = np.dot(x.T,(y_ - y))
  m = x.shape[0]
  return grad/m

def gradient_descent(x,y,learning_rate = 0.1,max_iters=300):
  n = x.shape[1]
  theta = np.zeros((n,))
  error_list = []
  for i in range(max_iters):
    e = error(x,y,theta)
    error_list.append(e)
    grad = gradient(x,y,theta)
    theta = theta - learning_rate*grad
  return theta,error_list

In [24]:
theta,error_list = gradient_descent(xtrain,ytrain)
y_ = []
for i in range(xtrain.shape[0]):
  pred = hypothesis(xtrain[i],theta)
  y_.append(pred)
y_ = np.array(y_)

In [25]:
theta

array([ 4.99096674, 29.68187118, 92.66247759,  8.28062089, 44.76773522,
        2.51916121])

In [26]:
def r2_score(y,y_):
  num = np.sum((y-y_)**2)
  denom = np.sum((y-y.mean())**2)
  score = 1 - num/denom
  return score*100

In [27]:
r2_score(ytrain,y_)

96.60939669975616

In [39]:
test

array([[ 1.01525387e+00,  2.07620944e+00, -2.66434820e-01,
        -2.41808820e+00, -9.80502790e-01],
       [-3.75021204e-01,  9.53184528e-01,  6.26719138e-01,
         7.04405750e-01, -3.55489211e-01],
       [-1.02445225e+00,  9.62991107e-01, -4.07942004e-01,
        -1.86127383e+00,  4.55201351e-01],
       ...,
       [ 5.54727647e-01,  1.76824345e+00, -8.97787210e-01,
        -1.19366107e+00,  3.40563374e-01],
       [-1.62717246e+00,  8.56470994e-01, -5.65729519e-04,
         6.29386649e-01,  4.53382144e-01],
       [ 1.39310499e-01,  5.31597186e-01, -8.53107053e-01,
         3.16920076e-02,  1.71489304e+00]])

In [40]:
ones = np.ones((test.shape[0],1))
test = np.hstack((ones,test))

In [42]:
xtrain

array([[ 1.        ,  0.29341624, -0.94559871, -0.42110515,  0.40681602,
         0.52566183],
       [ 1.        , -0.83608408, -0.18922804, -0.77640262, -1.05383124,
         0.59799685],
       [ 1.        ,  0.23642511,  0.13283602, -0.14772298,  0.69985396,
        -0.18736416],
       ...,
       [ 1.        ,  1.04417694, -0.89920649,  1.73039905, -1.87105676,
         0.44251965],
       [ 1.        , -1.2691729 , -0.00505216,  1.85766873, -1.08036482,
         0.73633394],
       [ 1.        , -1.88400025, -0.84942743, -1.45227035,  0.48861308,
         1.4595758 ]])

In [44]:
y_ = []
for i in range(test.shape[0]):
  pred = hypothesis(test[i],theta)
  y_.append(pred)
y_ = np.array(y_)

In [47]:
import csv
with open('Sample_Submission.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    m = y_.shape[0]
    writer.writerow(["id","target"])
    for i in range(m):
        l = [i,y_[i]]
        writer.writerow(l)
    csvFile.close()